name: CI

on:
  push:
    # branches: [main, gha]
  pull_request:

jobs:
  # build:
  #   name: "Build"
  #   steps:
  #     - uses: actions/checkout@v4
  # build-for-alpine-arm64:
  #   name: "Build for Alpine ARM64"
  #   steps:
  #     - uses: actions/checkout@v4
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm   
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.alpha_liu_01.SpeedyNote
          manifest-path: com.github.alpha_liu_01.SpeedyNote.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true
        continue-on-error: true
      - run: |
          sudo apt-get install tree
          sudo tree /__w
